BOARD = zcu102
#UBOOT_CONFIG = zc70x #TODO does it really matter?
UBOOT_CONFIG = zcu102
#BOARD_MODEL = xilinx.com:zc706:part0:1.0
BOARD_MODEL = xilinx.com:zcu102:part0:3.0
#PART = xc7z045ffg900-2
PART = xczu9eg-ffvb1156-2-i

#include ../common/Makefrag
include ../common/Makefrag.zcu
