open_project zcu102_rocketchip_ZynqConfig/zcu102_rocketchip_ZynqConfig.xpr
reset_run synth_1
reset_run impl_1
launch_runs synth_1
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream
wait_on_run impl_1
exit
