  set_property -dict [ list \
CONFIG.PSU__CAN0__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__CAN0__PERIPHERAL__IO {MIO 38 .. 39} \
CONFIG.PSU__CAN1__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__CAN1__PERIPHERAL__IO {MIO 32 .. 33} \
CONFIG.PSU__DP__LANE_SEL {Single Lower} \
CONFIG.PSU__DISPLAYPORT__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__DPAUX__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__DPAUX__PERIPHERAL__IO {EMIO} \
CONFIG.PSU__ENET2__GRP_MDIO__ENABLE {1} \
CONFIG.PSU__ENET2__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__GPIO0_EMIO__PERIPHERAL__ENABLE {0} \
CONFIG.PSU__GPIO0_MIO__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__GPIO1_MIO__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__I2C0__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__I2C0__PERIPHERAL__IO {MIO 6 .. 7} \
CONFIG.PSU__NAND__CHIP_ENABLE__ENABLE {1} \
CONFIG.PSU__NAND__DATA_STROBE__ENABLE {1} \
CONFIG.PSU__NAND__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__NAND__READY0_BUSY__ENABLE {1} \
CONFIG.PSU__NAND__READY1_BUSY__ENABLE {1} \
CONFIG.PSU__PCIE__LANE0__ENABLE {1} \
CONFIG.PSU__PCIE__LANE0__IO {GT Lane0} \
CONFIG.PSU__PCIE__MAXIMUM_LINK_WIDTH {x1} \
CONFIG.PSU__PCIE__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__PJTAG__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__PJTAG__PERIPHERAL__IO {MIO 26 .. 29} \
CONFIG.PSU__PMU__GPI0__ENABLE {0} \
CONFIG.PSU__PMU__GPI1__ENABLE {0} \
CONFIG.PSU__PMU__GPI2__ENABLE {0} \
CONFIG.PSU__PMU__GPI3__ENABLE {0} \
CONFIG.PSU__PMU__GPI4__ENABLE {0} \
CONFIG.PSU__PMU__GPO0__ENABLE {0} \
CONFIG.PSU__PMU__GPO1__ENABLE {0} \
CONFIG.PSU__PMU__GPO2__ENABLE {0} \
CONFIG.PSU__PMU__GPO3__ENABLE {0} \
CONFIG.PSU__PMU__GPO4__ENABLE {0} \
CONFIG.PSU__PMU__GPO5__ENABLE {0} \
CONFIG.PSU__PMU__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__SPI0__GRP_SS0__ENABLE {1} \
CONFIG.PSU__SPI0__GRP_SS1__ENABLE {1} \
CONFIG.PSU__SPI0__GRP_SS1__IO {MIO 2} \
CONFIG.PSU__SPI0__GRP_SS2__ENABLE {1} \
CONFIG.PSU__SPI0__GRP_SS2__IO {MIO 1} \
CONFIG.PSU__SPI0__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__SPI0__PERIPHERAL__IO {MIO 0 .. 5} \
CONFIG.PSU__SPI1__GRP_SS0__ENABLE {1} \
CONFIG.PSU__SPI1__GRP_SS0__IO {MIO 47} \
CONFIG.PSU__SPI1__GRP_SS1__ENABLE {1} \
CONFIG.PSU__SPI1__GRP_SS1__IO {MIO 46} \
CONFIG.PSU__SPI1__GRP_SS2__ENABLE {1} \
CONFIG.PSU__SPI1__GRP_SS2__IO {MIO 45} \
CONFIG.PSU__SPI1__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__SPI1__PERIPHERAL__IO {MIO 44 .. 49} \
CONFIG.PSU__UART0__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__UART0__PERIPHERAL__IO {MIO 42 .. 43} \
CONFIG.PSU__UART1__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__UART1__PERIPHERAL__IO {MIO 40 .. 41} \
CONFIG.PSU__USB1__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__USB2_1__EMIO__ENABLE {0} \
 ] [get_bd_cells zynq_ultra_ps_e_0]

  save_bd_design
