  set_property -dict [ list \
CONFIG.PSU__ENET0__GRP_MDIO__ENABLE {1} \
CONFIG.PSU__ENET0__GRP_MDIO__IO {MIO 76 .. 77} \
CONFIG.PSU__ENET0__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__ENET0__PERIPHERAL__IO {MIO 26 .. 37} \
CONFIG.PSU__GPIO0_MIO__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__GPIO1_MIO__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__I2C1__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__I2C1__PERIPHERAL__IO {MIO 4 .. 5} \
CONFIG.PSU__NAND__CHIP_ENABLE__ENABLE {1} \
CONFIG.PSU__NAND__CHIP_ENABLE__IO {MIO 9} \
CONFIG.PSU__NAND__DATA_STROBE__ENABLE {1} \
CONFIG.PSU__NAND__DATA_STROBE__IO {MIO 12} \
CONFIG.PSU__NAND__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__NAND__PERIPHERAL__IO {MIO 13 .. 25} \
CONFIG.PSU__NAND__READY0_BUSY__ENABLE {1} \
CONFIG.PSU__NAND__READY1_BUSY__ENABLE {1} \
CONFIG.PSU__NAND__READY0_BUSY__IO {MIO 10} \
CONFIG.PSU__NAND__READY1_BUSY__IO {MIO 11} \
CONFIG.PSU__PJTAG__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__PJTAG__PERIPHERAL__IO {MIO 0 .. 3} \
CONFIG.PSU__SD1__GRP_CD__ENABLE {1} \
CONFIG.PSU__SD1__GRP_CD__IO {MIO 45} \
CONFIG.PSU__SD1__GRP_POW__ENABLE {1} \
CONFIG.PSU__SD1__GRP_POW__IO {MIO 43} \
CONFIG.PSU__SD1__GRP_WP__ENABLE {1} \
CONFIG.PSU__SD1__GRP_WP__IO {MIO 44} \
CONFIG.PSU__SD1__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__SD1__PERIPHERAL__IO {MIO 46 .. 51} \
CONFIG.PSU__SD1__SLOT_TYPE {SD 2.0} \
CONFIG.PSU__UART0__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__UART0__PERIPHERAL__IO {MIO 6 .. 7} \
CONFIG.PSU__USB0__REF_CLK_FREQ {26} \
CONFIG.PSU__USB1__REF_CLK_FREQ {26} \
CONFIG.PSU__USB0__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__USB0__PERIPHERAL__IO {MIO 52 .. 63} \
CONFIG.PSU__USB1__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__USB1__PERIPHERAL__IO {MIO 64 .. 75} \
CONFIG.PSU__USB3_0__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__USB3_0__PERIPHERAL__IO {GT Lane0} \
CONFIG.PSU__USB3_1__PERIPHERAL__ENABLE {1} \
CONFIG.PSU__USB3_1__PERIPHERAL__IO {GT Lane3} \
CONFIG.PSU__USB3_0__EMIO__ENABLE {0} \
CONFIG.PSU__SATA__REF_CLK_FREQ {150} \
CONFIG.PSU__SATA__LANE0__ENABLE {1} \
CONFIG.PSU__SATA__LANE0__IO {GT Lane2} \
CONFIG.PSU__SATA__LANE1__ENABLE {1} \
CONFIG.PSU__SATA__LANE1__IO {GT Lane1} \
CONFIG.PSU__SATA__PERIPHERAL__ENABLE {1} \
   ] [get_bd_cells zynq_ultra_ps_e_0]

  save_bd_design
